const baseDeDados = `Nome, Autor, Ano, Descrição, ISBN
"Caminhos Entrelaçados", "Isabella Mendes", 2022, "Uma história envolvente de amor e amizade que se desenrola em meio aos desafios da vida moderna. Os personagens descobrem que seus destinos estão mais interligados do que poderiam imaginar.", 978-1234567890
"O Mistério da Lua Dourada", "Gabriel Silva", 2018, "Uma emocionante aventura em busca de um tesouro lendário escondido por gerações. Os protagonistas enfrentam enigmas e perigos enquanto seguem as pistas que os levam à Lua Dourada.", 978-9876543210
"Segredos do Além", "Sofia Almeida", 2015, "Um thriller psicológico que explora os limites entre o real e o imaginário. À medida que os personagens mergulham em suas próprias mentes, segredos sombrios vêm à tona.", 978-5432109876
"O Refúgio das Estrelas", "Lucas Pereira", 2020, "Uma jornada emocionante pelo espaço sideral, onde a tripulação de uma nave espacial busca um novo lar para a humanidade. No caminho, eles encontram desafios cósmicos e dilemas éticos.", 978-6789012345
"Renascer da Aurora", "Beatriz Santos", 2017, "Um romance histórico que se passa durante um período de transformação social. A personagem principal luta para encontrar seu lugar em meio a reviravoltas políticas e mudanças culturais.", 978-0123456789
"A Lenda do Horizonte", "Ricardo Oliveira", 2005, "Uma fábula encantadora que segue os passos de um jovem aventureiro em busca do lendário Horizonte, enfrentando criaturas mágicas e desafios emocionantes.", 978-7654321098
"Espíritos da Floresta", "Ana Ferreira", 2013, "Uma história ambientada em uma floresta encantada, onde os personagens se conectam com a natureza e com os espíritos que a habitam, aprendendo lições valiosas sobre equilíbrio e respeito.", 978-0987654321
"O Enigma do Relógio", "Fernando Costa", 2019, "Um mistério intrincado que gira em torno de um relógio misterioso encontrado em um antiquário. À medida que os protagonistas desvendam seus segredos, eles se veem envolvidos em uma conspiração surpreendente.", 978-2345678901
"Além das Estrelas", "Mariana Lima", 2008, "Uma viagem intergaláctica que leva os leitores por mundos desconhecidos e civilizações alienígenas. A narrativa explora questões de identidade, pertencimento e a busca por nosso lugar no universo.", 978-8765432109
"Coração de Cristal", "André Ribeiro", 2016, "Um conto de fantasia que segue uma jovem destinada a salvar um reino mágico. Para cumprir sua missão, ela deve encontrar o lendário Coração de Cristal, enfrentando desafios épicos e descobrindo sua própria coragem interior.", 978-3456789012
"Sombras do Passado", "Carla Andrade", 2014, "Um romance histórico que mergulha nos segredos de uma família aristocrática em tempos turbulentos. Intrigas, paixões proibidas e reviravoltas dramáticas são tecidas em meio a cenários deslumbrantes.", 978-5678901234
"O Último Portal", "Pedro Carvalho", 2009, "Uma jornada emocionante por dimensões alternativas e mundos mágicos. Quando um portal que liga esses reinos é ameaçado, um grupo de heróis improváveis embarca em uma busca para salvar a realidade como a conhecemos.", 978-7890123456
"O Segredo do Relicário", "Isabel Oliveira", 2011, "Um enigma que se desenrola através dos séculos, ligando um relicário sagrado a eventos históricos e mistérios ocultos. A protagonista descobre uma rede de segredos que abrange gerações e culturas.", 978-9012345678
"Voo das Borboletas", "Rafaela Sousa", 2010, "Uma narrativa cativante sobre a jornada de transformação de uma jovem tímida e insegura. À medida que ela enfrenta desafios pessoais e encontra novas amizades, sua jornada é simbolizada pelo voo gracioso das borboletas.", 978-1234567890
"O Mistério do Farol", "Gustavo Marques", 2012, "Um suspense envolvente que se passa em um farol isolado na costa. Quando eventos estranhos começam a acontecer, o protagonista se vê envolvido em uma busca por respostas que revelam segredos sombrios e perturbadores.", 978-2345678901
"Destino Entrelaçado", "Carolina Cruz", 2021, "Um romance épico que transcende o tempo e o espaço, unindo duas almas destinadas a se encontrarem em diferentes vidas e realidades. A narrativa explora a conexão profunda que vai além das fronteiras do tempo.", 978-3456789012
"O Tesouro Perdido de Eldoria", "Hugo Martins", 2018, "Uma aventura emocionante em busca de um tesouro lendário escondido em um reino mágico. Os personagens enfrentam desafios épicos e descobertas surpreendentes enquanto exploram as terras de Eldoria.", 978-4567890123
"O Pacto das Sombras", "Lúcia Silva", 2013, "Um thriller sobrenatural que segue um detetive enquanto ele investiga uma série de crimes inexplicáveis. À medida que ele mergulha no submundo das sombras, descobre um pacto sombrio que ameaça a cidade.", 978-5678901234
"O Legado da Estrela Negra", "Rodrigo Alves", 2017, "Uma fantasia épica que segue o último guardião de uma joia mágica conhecida como Estrela Negra. Ele é encarregado de proteger o mundo de forças sombrias que buscam controlar seu poder imenso.", 978-7890123456
`


